# $FreeBSD$

PKGNAMESUFFIX=	-${MODEL}

COMMENT=	Cross-build U-Boot loader for OrangePi Plus 2E

LICENSE=	GPLv2

MASTERDIR=	${.CURDIR}/../u-boot-olimex-a20-som-evb
DESCR=		${.CURDIR}/pkg-descr
MODEL=		orangepi-plus-2e
BOARD_CONFIG=	orangepi_pc_defconfig

.include "${MASTERDIR}/Makefile"
